SOTA/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SOTA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SOTA.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        
        private SotaContext db;
        public AdminController(SotaContext context)
        {
            var b = 1;
            var a = 1;
            db = context;
        }

        public IActionResult Users()
        {
            string login = HttpContext.User.Identity.Name;
            //  Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            ListUsersAdmin listUsersAdmin = new ListUsersAdmin(db);
            listUsersAdmin.LisrUsersA();
            UsersPage usersPage = new UsersPage();
            usersPage.LisrUsersMO = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 3).OrderBy(x => x.IdMo).ToList();
            usersPage.LisrUsersOO = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 2).OrderBy(x => x.IdMo).ToList();
            usersPage.LisrUsersKlass = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 1).OrderBy(x => x.IdMo).ThenBy(x => x.IdOo).ToList();
            // usersPage.LisrUsersTest = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 0).ToList();
            // LisrUsersA listMo = new ListUsersMo();
            //listMo.UsersMo = db.Users.Where(p => p.Role == 3).ToList();
            return View("Users", usersPage);
        }

        public IActionResult UO()
        {
            string login = HttpContext.User.Identity.Name;
            Users user = db.Users.Where(p => p.Name == login).First();
            int ImO = user.IdMo;
            ViewBag.rl = user.Role;
            ListUsersAdmin listUsersAdmin = new ListUsersAdmin(db);
            listUsersAdmin.LisrUsersA();
            UsersPage usersPage = new UsersPage();
            usersPage.LisrUsersOO = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 2 && x.IdMo == ImO).OrderBy(x => x.IdMo).ToList();
            return View("UO", usersPage);
        }

        public IActionResult OO()
        {
            string login = HttpContext.User.Identity.Name;
            Users user = db.Users.Where(p => p.Name == login).First();
            int IoO = user.IdOo;
            ViewBag.rl = user.Role;
            ListUsersAdmin listUsersAdmin = new ListUsersAdmin(db);
            listUsersAdmin.LisrUsersA();
            UsersPage usersPage = new UsersPage();
            usersPage.LisrUsersKlass = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 1 && x.IdOo == IoO).OrderBy(x => x.Klass).ToList();
            usersPage.LisrUsersTest = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 0 && x.IdOo == IoO).OrderBy(x => x.Klass).ThenBy(x => x.F).ToList();
            return View("OO", usersPage);
        }

        /*    public IActionResult Klass()
            {
                string login = HttpContext.User.Identity.Name;
                Users user = db.Users.Where(p => p.Name == login).First();
                int ImKlass = user.IdKlass;
                ViewBag.rl = user.Role;
                ListUsersAdmin listUsersAdmin = new ListUsersAdmin(db);
                listUsersAdmin.GetRab(user.IdMo, user.IdOo, user.IdKlass);
                if (listUsersAdmin.rabList == null)
                {
                    listUsersAdmin.LisrUsersA();
                }
                else
                {
                    listUsersAdmin.LisrUsersA(listUsersAdmin.rabList.Last().Id);
                    ViewBag.last = listUsersAdmin.rabList.Last().Id;
                }
                UsersPage usersPage = new UsersPage();
                usersPage.rabotaKlasss = listUsersAdmin.rabList;
                usersPage.LisrUsersTest = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 0 && x.IdKlass == ImKlass).OrderBy(x => x.Klass).ToList();

                return View("Klass", usersPage);
            }*/

        public IActionResult Klass(UsersPage page)
        {
            string login = HttpContext.User.Identity.Name;
            Users user = db.Users.Where(p => p.Name == login).First();
            int ImKlass = user.IdKlass;
            ViewBag.rl = user.Role;
            ListUsersAdmin listUsersAdmin = new ListUsersAdmin(db);
            listUsersAdmin.GetRab(user.IdMo, user.IdOo, user.IdKlass);
            int id_spec=0;
                string name="";
            if (listUsersAdmin.rabList != null)
            {
                listUsersAdmin.rabList.OrderBy(x => x.Konec);
            
             id_spec = listUsersAdmin.rabList.OrderByDescending(x => x.Konec).First().Id;
             name = listUsersAdmin.rabList.OrderByDescending(x => x.Konec).First().Name;
            }
            if (listUsersAdmin.rabList == null)
            {
                listUsersAdmin.LisrUsersA();
            }
            else
            {

                listUsersAdmin.LisrUsersA(id_spec);
                ViewBag.last = name;
            }
            UsersPage usersPage = new UsersPage();
            usersPage.rabotaKlasss = listUsersAdmin.rabList;
            usersPage.LisrUsersTest = listUsersAdmin.LisrUsersAdm.Where(x => x.Role == 0 && x.IdKlass == ImKlass).OrderBy(x => x.Klass).ToList();

            return View("Klass", usersPage);
        }


        public IActionResult CleanPass(int idDel, int role)
        {
            if (role == 4)
            {
                Users user = new Users();
                user = db.Users.FirstOrDefault(u => u.Id == idDel);
                user.Pass = null;
                user.DateReg = DateTime.MinValue;
                db.SaveChanges();
                return Redirect("Users");
            }
            if (role == 3)
            {
                Users user = new Users();
                user = db.Users.FirstOrDefault(u => u.Id == idDel);
                user.Pass = null;
                user.DateReg = DateTime.MinValue;
                db.SaveChanges();
                return Redirect("UO");
            }
            if (role == 2)
            {
                Users user = new Users();
                user = db.Users.FirstOrDefault(u => u.Id == idDel);
                user.Pass = null;
                user.DateReg = DateTime.MinValue;
                db.SaveChanges();
                return Redirect("OO");
            }
            if (role == 1)
            {
                Users user = new Users();
                user = db.Users.FirstOrDefault(u => u.Id == idDel);
                user.Pass = null;
                user.DateReg = DateTime.MinValue;
                db.SaveChanges();
                return Redirect("Klass");
            }
            else
            {
                return Redirect("Index");
            }
        }

        public IActionResult RazrReg(int idReg, int role)
        {
            if (role == 4)
            {
                Users user = new Users();
                user = db.Users.FirstOrDefault(u => u.Id == idReg);
                user.Kod = "0";
                db.SaveChanges();
                return Redirect("Users");
            }
            if (role == 3)
            {
                Users user = new Users();
                user = db.Users.FirstOrDefault(u => u.Id == idReg);
                user.Kod = "0";
                db.SaveChanges();
                return Redirect("UO");
            }
            if (role == 2)
            {
                Users user = new Users();
                user = db.Users.FirstOrDefault(u => u.Id == idReg);
                user.Kod = "0";
                db.SaveChanges();
                return Redirect("OO");
            }
            if (role == 1)
            {
                Users user = new Users();
                user = db.Users.FirstOrDefault(u => u.Id == idReg);
                user.Kod = "0";
                db.SaveChanges();
                return Redirect("Klass");
            }
            else
            {
                return Redirect("Index");
            }
        }

        public async Task<IActionResult> LoadUsers(IList<IFormFile> uploadedFile)
        {



            if (uploadedFile != null)
            {
                foreach (var file in uploadedFile)
                {
                    ReadExcel readExcel = new ReadExcel(file);
                    var _ListExcel = readExcel.ListExcel();
                    LoadVBD loadVBD = new LoadVBD(_ListExcel, db);
                    loadVBD.CreateMO();
                }
            }

            return Redirect("Users");
        }

    }
}

SOTA/Controllers/RabotaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SOTA.Models;
using SOTA.Models.Pages.Test;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
//TODO: Скрывать прошедшие работы поле в базе hiden, в таблиу добавить chekbox 

namespace SOTA.Controllers
{
    [Authorize]
    public class RabotaController : Controller
    {
        SotaContext db;
        string error;
        public RabotaController(SotaContext context)
        {
            db = context;
        }
        // [HttpGet]
        //[Route("Rabota/RabotaAdd/")]
        public IActionResult RabotaAdd()
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            ViewData["Predms"] = db.Predm.ToList();
            ViewData["TipSpecs"] = db.TipSpec.ToList();
            ViewData["SpisSpec"] = db.Specific;
            return View();
        }

        //[Route("Rabota/RabotaAdd/{IdRabota?}")]
        //  [HttpPost]

        public IActionResult CleanAllStaticSpec()
        {
            StaticRabotsOtvVBD.CleanStaticOtvVBDs();
            return RedirectToAction("RabotaList");
        }


        public IActionResult RabotaSozdan()
        {
            Rabota rabota = new Rabota();
            db.Rabota.Add(rabota);
            db.SaveChanges();
            int IdRabota = rabota.Id;
            return RedirectToAction("RabotaRedact", new { IdRabota });
        }

        public IActionResult RabotaRedact(int IdRabota)
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            SborkaRabotaRedact sbor = new SborkaRabotaRedact(db, IdRabota);
            RabotaRedact rabota = sbor.GetRabotaRedact();






            // ViewData["TipSpecs"] = db.TipSpec.ToList();


            return View(rabota);

        }
        public IActionResult RabotaList()
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            RabotaList rabotaList = new RabotaList();


            rabotaList.Rabotas = db.Rabota.Select(x => new WorkNotEnd { Id = x.Id, IdSpec = x.IdSpec, Dliteln = x.Dliteln, Klass = x.Klass, Konec = x.Konec, ListUchasn = x.ListUchasn, Nachalo = x.Nachalo, Name = x.Name, Sozd = x.Sozd, UrovenRabot = x.UrovenRabot, CountNotEnd = db.VariantUser.Count(y => y.IdRabota == x.Id && y.Konec == 0) }).ToList();

            return View(rabotaList);
        }
        public async Task<IActionResult> CalucaltionWork()
        {

            return RedirectToAction("RabotaList");

        }

        public async Task<IActionResult> RabotaNaznach(RabotaRedact rabota)
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);




            db.Update(rabota.Rabot).State = EntityState.Modified;
            //db.Rabota.Update(AddRabota);

            await db.SaveChangesAsync().ConfigureAwait(false);
            if (rabota.Rabot.UrovenRabot == "Край")
            {
                DelNaznach(rabota.Rabot.Id);
            }

            return RedirectToAction("RabotaList");

        }
       
        public async Task<IActionResult> Variants(int idRabota)
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            Variants model = new Variants(idRabota, db);
            return View("Variants", model);
        }
        public async Task<IActionResult> Variant(int nVar, int idSpec)
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            Variant variant = new Variant(idSpec, nVar, db);
            return View("Variant", variant);
        }

        public IActionResult RabotaDel(int[] Id)
        {
            for (int i = 0; i < Id.Length; i++)
            {
                Rabota rabota = new Rabota { Id = Id[i] };
                db.Rabota.Remove(rabota);
                DelNaznach(Id[i]);
            }
            db.SaveChanges();

            return Json("ok");
        }

        public void DelNaznach(int id)
        {
            List<NaznachMo> Naznac = db.NaznachMo.Where(x => x.IdRab == id).ToList();
            db.NaznachMo.RemoveRange(Naznac);
            List<NaznachOo> NaznacOO = db.NaznachOo.Where(x => x.IdRab == id).ToList();
            db.NaznachOo.RemoveRange(NaznacOO);
            db.SaveChanges();
        }


        public IActionResult NaznachOO(int[] naz, int id)
        {
            DelNaznach(id);
            for (int i = 0; i < naz.Length; i++)
            {
                NaznachOo naznachOo = new NaznachOo();
                naznachOo.IdOo = naz[i];
                naznachOo.IdRab = id;
                db.NaznachOo.Add(naznachOo);
            }
            db.SaveChanges();
            return Json("Ok");
        }

        public IActionResult NaznachMO(int[] naz, int id)
        {
            DelNaznach(id);
            for (int i = 0; i < naz.Length; i++)
            {
                NaznachMo naznachMo = new NaznachMo();
                naznachMo.IdMo = naz[i];
                naznachMo.IdRab = id;
                db.NaznachMo.Add(naznachMo);
            }
            db.SaveChanges();
            return Json("Ok");
        }
    }
}

SOTA/Controllers/UchenController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SOTA.Models;
using System;
using System.Linq;

namespace SOTA.Controllers
{
    [Authorize]
    public class UchenController : Controller
    {
        SotaContext db;

        public UchenController(SotaContext context)
        { nf=1;
            db = context;
        }
        // [HttpGet]
        //[Route("Rabota/RabotaAdd/")]
        [Authorize]
        public IActionResult NaznacRabotaList()
        {

            var login = HttpContext.User.Identity.Name;
            Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = user.Role;
            FormirRabotaTablList formir = new FormirRabotaTablList(user, db);
            RabotaUchenList rabotaList = new RabotaUchenList();

            rabotaList = formir.GetSpisokRabotUchen();


            return View(rabotaList);
        }
    }
}

SOTA/Views/UprSpec/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - СОТА</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/all.css" />
    <link rel="stylesheet" href="~/css/main.css" />
   
</head>
<body style="background-color:azure">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">СОТА</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UprSpec" asp-action="SpecifikacList">Спецификация</a>
                        </li>
                        @if (User.Identity.IsAuthenticated == false)
                        {
                            <li class="nav-item" style="margin:5px; margin-left:auto;">
                                <a asp-controller="Account" asp-action="Login">Войти </a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item" style="margin:5px; margin-left:auto;">
                                <a asp-controller="Account" asp-action="Logout">Выйти </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SOTA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    
    <environment include="Development">
        @*<script type="text/javascript" src="~/UprSpec/scripts/jquery-2.x-git.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    @* <environment exclude="Development">
                 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
                </script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
                </script>
        </environment>*@
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@

    @RenderSection("Scripts", required: false)
</body>
</html>

SOTA/Views/UprSpec/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - СОТА</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/all.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/util.css" />
    <link rel="stylesheet" href="~/css/daterangepicker.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/moment.min.js" asp-append-version="true"></script>
    <script src="~/js/daterangepicker.js" asp-append-version="true"></script>

</head>
<body class="bg-custom-2">
    <header>
        <div id="topheader">
            <nav class="navbar navbar-light  navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container ">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/favicon.png" width="30" height="30" alt="logo">
                        СОТА
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse navbar-expand-lg collapse ">
                        <ul class="nav navbar-nav flex-grow-1 nav-pills">

                            @if (ViewBag.rl == 1)
                            {
                            <li class="nav-item ">

                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rabota" asp-action="RabotaList">Работы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SpecList" asp-action="SpecifikacList">Спецификации</a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Задания</a>
                                </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Test">Отчеты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Users">Пользователи</a>
                            </li>
                            }
                            else
                            {
                            <li class="nav-item active">

                                <a class="nav-link text-dark" asp-area="" asp-controller="Uchen" asp-action="NaznacRabotaList">Главная</a>
                            </li>
                            }
                        </ul>
                        <ul class="nav navbar-nav flex-grow-1 nav-pills  navbar-right">
                            @if (User.Identity.IsAuthenticated == false)
                            {
                            <li class="nav-item " style="margin:5px; margin-left:auto;">
                                <a asp-controller="Account" class="nav-link text-dark" asp-action="Login">Войти </a>
                            </li>

                            }
                            else
                            {
                            <li class="nav-item" style="margin:5px; margin-left:auto;">
                                <a asp-controller="Account" class="nav-link text-dark" asp-action="Logout">Выйти </a>
                            </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SOTA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    @*<environment include="Development">
            <script type="text/javascript" src="~/UprSpec/scripts/jquery-2.x-git.js"></script>

        </environment>*@
    @* <environment exclude="Development">
                 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
                </script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
                </script>
        </environment>*@
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@

    @RenderSection("Scripts", required: false)
</body>
</html>