SOTA/Models/Pages/RabotaList.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace SOTA.Models
{

    public class RabotaUchen
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdSpec { get; set; }
        public int Dliteln { get; set; }
        public string UrovenRabot { get; set; }
        public DateTime Nachalo { get; set; }
        public DateTime Konec { get; set; }
        public string ListUchasn { get; set; }
        public DateTime Sozd { get; set; }
        // public int SpecId { get; set; }
        public string SpecN { get; set; }
        public string TipN { get; set; }
        public string PredmN { get; set; }
        public int KlassR { get; set; }

    }

    public class ReportsRabotaList
    {
        public int idOO { get; }
        public List<RabotaUchen> RabotaTabls { get; set; }
    }


    public class RabotaUchenList
    {
        public List<RabotaUchen> RabotaTabls { get; set; }
    }

    public class FormirRabotaTablList
    {

        //  Users User;
        SotaContext _db;
        DateTime dateNow;
        int _idOO;
        int _idMO;
        int klass;
        int role;
        public FormirRabotaTablList()
        {

        }
        public FormirRabotaTablList(Users user, SotaContext db)
        {
            _db = db;

            _idOO = user.IdOo;
            _idMO = user.IdMo;

            dateNow = DateTime.Now;
            klass = db.Klass.Find(user.IdKlass).KlassNom;

        }
        public FormirRabotaTablList(int idOO, SotaContext db)
        {
            _db = db;
            _idOO = idOO;
            _idMO = db.Oo.Where(x => x.Id == idOO).First().IdMo;
            dateNow = DateTime.Now;
        }

        public FormirRabotaTablList(Mo MO, SotaContext db)
        {
            _db = db;
            _idOO = 0;
            _idMO = MO.Id;
            dateNow = DateTime.Now;
        }

        public FormirRabotaTablList(SotaContext db)
        {
            _db = db;
            _idOO = 0;
            dateNow = DateTime.Now;
            role = 4;
        }

        public RabotaUchenList GetSpisokRabotUchen()
        {
            RabotaUchenList rabotaList = new RabotaUchenList();
            _db.Rabota.Where(x => x.Klass == klass /*&& x.Konec > dateNow*/).ToList();
            List<Rabota> list;
            if (role == 4)
            {
                list = _db.Rabota.ToList();
            }
            else
            {
                list = GetSpisokRabot(_db.Rabota.Where(x => x.Klass == klass /*&& x.Konec > dateNow*/).ToList());
            }
            if (list.Count != 0)
                rabotaList.RabotaTabls = (from rab in list

                                          join SpecK in _db.Specific on rab.IdSpec equals SpecK.Id into spK
                                          from SK in spK.DefaultIfEmpty()
                                          join Pred in _db.Predm on SK.Predm equals Pred.Id into pr
                                          from Predm in pr.DefaultIfEmpty()
                                          join Tip in _db.TipSpec on SK.Tip equals Tip.Id into T
                                          from Tip in T.DefaultIfEmpty()



                                          select new RabotaUchen
                                          {
                                              Id = rab.Id,
                                              Name = rab.Name,
                                              Dliteln = rab.Dliteln,
                                              Nachalo = rab.Nachalo,
                                              Konec = rab.Konec,
                                              PredmN = Predm.Name,
                                              TipN = Tip.Name
                                          }).ToList();

            return rabotaList;
        }

        public ReportsRabotaList GetSpisokRabotReports()
        {
            ReportsRabotaList rabotaList = new ReportsRabotaList();
            List<Rabota> list;
            if (role == 4)
            {
                _db.Rabota.Where(x => x.Konec < dateNow).ToList();
                list = _db.Rabota.ToList();
            }
            else
            {
                _db.Rabota.Where(x => x.Klass == klass && x.Konec < dateNow).ToList();
                list = _db.Rabota.Where(x => x.Konec < dateNow).ToList();
            }


            if (list.Count != 0)
                rabotaList.RabotaTabls = (from rab in list

                                          join SpecK in _db.Specific on rab.IdSpec equals SpecK.Id into spK
                                          from SK in spK.DefaultIfEmpty()
                                          join Pred in _db.Predm on SK.Predm equals Pred.Id into pr
                                          from Predm in pr.DefaultIfEmpty()
                                          join Tip in _db.TipSpec on SK.Tip equals Tip.Id into T
                                          from Tip in T.DefaultIfEmpty()



                                          select new RabotaUchen
                                          {
                                              Id = rab.Id,
                                              Name = rab.Name,
                                              KlassR = rab.Klass,
                                              Nachalo = rab.Nachalo,
                                              Konec = rab.Konec,
                                              PredmN = Predm.Name,
                                              TipN = Tip.Name
                                          }).ToList();

            return rabotaList;
        }
        private List<Rabota> GetSpisokRabot(List<Rabota> list)
        {


            List<Rabota> ListRabot = new List<Rabota>();

            ListRabot.AddRange(GetSpisokRabotKray(list));
            ListRabot.AddRange(GetSpisokRabotMO(list));

            ListRabot.AddRange(GetSpisokRabotOO(list));


            return ListRabot;

        }
        private List<Rabota> GetSpisokRabotKray(List<Rabota> rabot)
        {
            var spisok = rabot.Where(x => x.UrovenRabot == "Край").ToList();
            return spisok;
        }
        private List<Rabota> GetSpisokRabotMO(List<Rabota> rabot)
        {
            var spisok = from Naznach in _db.NaznachMo.Where(x => x.IdMo == _idMO)

                         join Rab in rabot on Naznach.IdRab equals Rab.Id

                         select Rab;

            return spisok.ToList();
        }
        private List<Rabota> GetSpisokRabotOO(List<Rabota> rabot)
        {
            IQueryable<Rabota> spisok;
            if (_idOO != 0)
            {
                spisok = from Naznach in _db.NaznachOo.Where(x => x.IdOo == _idOO)

                         join Rab in rabot on Naznach.IdRab equals Rab.Id

                         select Rab;
            }
            else
            {
                spisok = from OO in _db.Oo.Where(x => x.IdMo == _idMO)
                         join Naznach in _db.NaznachOo on OO.Id equals Naznach.IdOo into naznach
                         from Naznach in naznach
                         join Rab in rabot on Naznach.IdRab equals Rab.Id into rab
                         from Rab in rab
                         select Rab

                     ;
            }
            return spisok.ToList();
        }

    }
   


    public class RabotaList
    {
        //
        public List<WorkNotEnd> Rabotas { get; set; }



    }


}

SOTA/Models/Pages/Reports/ReportGenerator.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace SOTA.Models.Pages.Reports
{

    public abstract class ReportGenerator
    {

        public abstract string Create();
        
    }

}

SOTA/Controllers/RabotaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SOTA.Models;
using SOTA.Models.Pages.Test;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
//TODO: Скрывать прошедшие работы поле в базе hiden, в таблиу добавить chekbox 

namespace SOTA.Controllers
{
    [Authorize]
    public class RabotaController : Controller
    {
        SotaContext db;
        string error;
        public RabotaController(SotaContext context)
        {
            db = context;
        }
        // [HttpGet]
        //[Route("Rabota/RabotaAdd/")]
        public IActionResult RabotaAdd()
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            ViewData["Predms"] = db.Predm.ToList();
            ViewData["TipSpecs"] = db.TipSpec.ToList();
            ViewData["SpisSpec"] = db.Specific;
            return View();
        }

        //[Route("Rabota/RabotaAdd/{IdRabota?}")]
        //  [HttpPost]

        public IActionResult CleanAllStaticSpec()
        {
            StaticRabotsOtvVBD.CleanStaticOtvVBDs();
            return RedirectToAction("RabotaList");
        }


        public IActionResult RabotaSozdan()
        {
            Rabota rabota = new Rabota();
            db.Rabota.Add(rabota);
            db.SaveChanges();
            int IdRabota = rabota.Id;
            return RedirectToAction("RabotaRedact", new { IdRabota });
        }

        public IActionResult RabotaRedact(int IdRabota)
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            SborkaRabotaRedact sbor = new SborkaRabotaRedact(db, IdRabota);
            RabotaRedact rabota = sbor.GetRabotaRedact();






            // ViewData["TipSpecs"] = db.TipSpec.ToList();


            return View(rabota);

        }
        public IActionResult RabotaList()
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            RabotaList rabotaList = new RabotaList();


            rabotaList.Rabotas = db.Rabota.Select(x => new WorkNotEnd { Id = x.Id, IdSpec = x.IdSpec, Dliteln = x.Dliteln, Klass = x.Klass, Konec = x.Konec, ListUchasn = x.ListUchasn, Nachalo = x.Nachalo, Name = x.Name, Sozd = x.Sozd, UrovenRabot = x.UrovenRabot, CountNotEnd = db.VariantUser.Count(y => y.IdRabota == x.Id && y.Konec == 0) }).ToList();

            return View(rabotaList);
        }
        public async Task<IActionResult> CalucaltionWork()
        {

            return RedirectToAction("RabotaList");

        }

        public async Task<IActionResult> RabotaNaznach(RabotaRedact rabota)
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);




            db.Update(rabota.Rabot).State = EntityState.Modified;
            //db.Rabota.Update(AddRabota);

            await db.SaveChangesAsync().ConfigureAwait(false);
            if (rabota.Rabot.UrovenRabot == "Край")
            {
                DelNaznach(rabota.Rabot.Id);
            }

            return RedirectToAction("RabotaList");

        }
       
        public async Task<IActionResult> Variants(int idRabota)
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            Variants model = new Variants(idRabota, db);
            return View("Variants", model);
        }
        public async Task<IActionResult> Variant(int nVar, int idSpec)
        {
            //string login = HttpContext.User.Identity.Name;
            //Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);
            Variant variant = new Variant(idSpec, nVar, db);
            return View("Variant", variant);
        }

        public IActionResult RabotaDel(int[] Id)
        {
            for (int i = 0; i < Id.Length; i++)
            {
                Rabota rabota = new Rabota { Id = Id[i] };
                db.Rabota.Remove(rabota);
                DelNaznach(Id[i]);
            }
            db.SaveChanges();

            return Json("ok");
        }

        public void DelNaznach(int id)
        {
            List<NaznachMo> Naznac = db.NaznachMo.Where(x => x.IdRab == id).ToList();
            db.NaznachMo.RemoveRange(Naznac);
            List<NaznachOo> NaznacOO = db.NaznachOo.Where(x => x.IdRab == id).ToList();
            db.NaznachOo.RemoveRange(NaznacOO);
            db.SaveChanges();
        }


        public IActionResult NaznachOO(int[] naz, int id)
        {
            DelNaznach(id);
            for (int i = 0; i < naz.Length; i++)
            {
                NaznachOo naznachOo = new NaznachOo();
                naznachOo.IdOo = naz[i];
                naznachOo.IdRab = id;
                db.NaznachOo.Add(naznachOo);
            }
            db.SaveChanges();
            return Json("Ok");
        }

        public IActionResult NaznachMO(int[] naz, int id)
        {
            DelNaznach(id);
            for (int i = 0; i < naz.Length; i++)
            {
                NaznachMo naznachMo = new NaznachMo();
                naznachMo.IdMo = naz[i];
                naznachMo.IdRab = id;
                db.NaznachMo.Add(naznachMo);
            }
            db.SaveChanges();
            return Json("Ok");
        }
    }
}

SOTA/Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SOTA.Models;
using SOTA.Models.Pages.Reports;
using System;
using System.Linq;
using SOTA.Models.Pages.Reports;
using System.Security.Claims;

namespace SOTA.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        SotaContext db;
        string error;
        public ReportController(SotaContext context)
        {
            db = context;
        }
        // [HttpGet]

        [Authorize]
        [Route("Report/ReportsList/")]
        public IActionResult ReportsList()
        {

            ViewBag.rl = Convert.ToInt16(HttpContext.User.Claims.First(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value);

            return View();
        }
        //
        [Route("Report/ReportsList/{tip?}")]
        public IActionResult ReportsList(int tip)
        {
            string login = HttpContext.User.Identity.Name;
            Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = user.Role;
            FormirRabotaTablList Tabl = new FormirRabotaTablList();
            var rabotaList = new ReportsRabotaList();
            if (user.Role == 2)
            {
                Tabl = new FormirRabotaTablList(user.IdOo, db);
                rabotaList = Tabl.GetSpisokRabotReports();
            }
            if (user.Role == 3)
            {
                Tabl = new FormirRabotaTablList(new Mo { Id = user.IdMo }, db);
                rabotaList = Tabl.GetSpisokRabotReports();
            }
            if (user.Role == 4)
            {
                Tabl = new FormirRabotaTablList(db);
                rabotaList = Tabl.GetSpisokRabotReports();
            }
            return View("RabotaList", rabotaList);
        }

        [Route("Report/Download/{IdRabota?}/{Tip?}")]
        public IActionResult Download(int IdRabota, int Tip)
        {
            string login = HttpContext.User.Identity.Name;
            Users user = db.Users.Where(p => p.Name == login).First();
            ViewBag.rl = user.Role;


            ReportGenerator Report;
            if (user.Role == 2)
            {
                Report = new ReportTip1(db, IdRabota, new Oo { Id = user.IdOo });
                return RedirectToAction("File", "Download", new { path = Report.Create() });
            }

            if (user.Role == 3)
            {
                Report = new ReportTip1(db, IdRabota, new Mo { Id = user.IdMo });
                return RedirectToAction("File", "Download", new { path = Report.Create() });
            }

            if (user.Role == 4)
            {
                //var mos = db.Mo.ToList();
                //for (int i = 0; i < mos.Count; i++)
                //{
                //    try
                //    {
                //        Report = new ReportTip1(db, IdRabota, new Mo { Id = mos[i].Id });
                //        RedirectToAction("File", "Download", new { path = Report.Create() });
                //    }
                //    catch
                //    { }
                //}
                Report = new ReportTip1(db, IdRabota, new Mo { Id = 0 });
                return RedirectToAction("File", "Download", new { path = Report.Create() });
            }


            return RedirectToAction("ReportsList");
        }
        public IActionResult SaveReport(int IdRabota)
        {

            return Json("Ok");
        }
    }
}

SOTA/Views/Report/RabotaList.cshtml
@model SOTA.Models.ReportsRabotaList

@{
    ViewData["Title"] = "Список работ";
}

<h1>Список работ</h1>
<form method="post">

    <div class="col-12 shadow p-3 mb-5 bg-white rounded">
       
        <div class="col-12 table-responsive-lg">
            <table class="table table-hover  table-sm table-bordered shadow align-content-center text-center">
                <thead class="table-yel">
                    <tr>

                        <th>Название работы</th>
                        <th>Предмет</th>
                        <th>Тип</th>
                        <th>Класс</th>
                        <th>Время начала</th>
                        <th>Время окончания</th>

                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @if (Model.RabotaTabls != null)
                    {
                        @foreach (var row in Model.RabotaTabls)

                        {

                    <tr>


                        <td>@row.Name</td>
                        <td>@row.PredmN</td>
                        <td>@row.TipN</td>
                        <td>@row.KlassR</td>

                        <td>@row.Nachalo</td>
                        <td>@row.Konec</td>
                        <td><a href="/Report/Download?IdRabota=@row.Id&Tip=1" class='btn btn-icon btn-sm btn-outline-yel text-left btn-block'><i class='fas fa-file-excel'></i>Скачать </a></td>

                    </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class=" text-right">
            <nav class="d-inline-block">
                <ul class="pagination mb-0">
                    <li class="page-item disabled">
                        <a class="page-link shadow" href="#" tabindex="-1"><i class="fas fa-chevron-left"></i></a>
                    </li>
                    <li class="page-item active"><a class="page-link shadow" href="#">1</a></li>
                    <li class="page-item">
                        <a class="page-link shadow" href="#">2</a>
                    </li>
                    <li class="page-item "><a class="page-link shadow" href="#">3</a></li>
                    <li class="page-item ">
                        <a class="page-link shadow" href="#"><i class="fas fa-chevron-right"></i></a>
                    </li>
                </ul>
            </nav>
        </div>

    </div>
    <script>
        function Del() {
            var a = document.querySelectorAll('input.DEL:checked');
            var outMO = []; //выходной массив
            for (var x = 0; x < a.length; x++) { //перебераем все объекты
                outMO.push(a[x].value); //добавляем значения в выходной массив
            }
            console.log(outMO);

            jQuery.ajax({
                url: '/Rabota/RabotaDel/',
                type: "POST",
                dataType: "json",
                data: { Id: outMO },
                success: function (query) {
                    alert("Запись удалена");
                    location.reload();
                }

            });
        }
    </script>
</form>

SOTA/Views/Report/ReportsList.cshtml
@model SOTA.Models.RabotaUchenList

@{
    ViewData["Title"] = "Отчеты по работам";
}

<h1>Список отчетов</h1>
<form method="post">

    <div class="col-12 shadow p-3 mb-5 bg-white rounded">
        @*<div class="col-12">
                <a id="AddSpec" class="btn btn-outline-success col-3" asp-area="" asp-controller="Rabota" asp-action="RabotaAdd"><i class='fas fa-plus-circle'></i>    Назначить</a>
                <a id="AddSpec" class="btn btn-outline-danger col-3" asp-area="" asp-controller="Rabota" asp-action="RabotaDel"><i class='fas fa-trash'></i>     Удалить</a>
            </div>*@
        @if (ViewBag.rl == 2 || ViewBag.rl == 3)
        {
            <div class="col-12 table-responsive-lg">
                <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-route-tip="1" asp-action="ReportsList">Протокол проведения монитороинговой работы</a>
            </div>
        }
        @if (ViewBag.rl == 4)
        {
            <div class="col-12 table-responsive-lg">
                <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-route-tip="1" asp-action="ReportsList">Протокол проведения монитороинговой работы</a>
            </div>
        }
    </div>
</form>